### ISSUE TITLE
Can I expose the k8s control plane itself?

### ISSUE THREAD

**Issue by russorat** [ngrok/kubernetes-ingress-controller#307]
### Description

My main question is this, the ingress controller is great for exposing a Kubernetes service, but is there a clean/recommended way to expose the control plane itself? Ideally, I'd love to run kubectl commands outside of my home network on my home cluster, using ngrok. Also would love to deploy to my home cluster with a CICD tool like CircleCI. If you have some time, please let me know your thoughts. Again, thanks for the service!

**Comment by jrobsonchase** [comment]
I've managed to get this working with a TLS edge and the following tunnel resource definition:

```yaml
apiVersion: ingress.k8s.ngrok.com/v1alpha1
kind: Tunnel
metadata:
  finalizers:
  - k8s.ngrok.com/finalizer
  name: k8s-control
  namespace: ngrok-ingress-controller
  resourceVersion: "900"
spec:
  backend:
    protocol: TCP
  forwardsTo: kubernetes.default.svc:443
  labels:
    edge: k8s-control # replace with your label as needed
```

The TLS edge needs to have TLS termination set to "pass through"

![2023-10-04-124405_1141x330_scrot](https://github.com/ngrok/kubernetes-ingress-controller/assets/1553581/639e22bd-6fd9-41fd-802c-5a06ba3d9aa8)

and you need to tell kubectl to skip verification of the server certificate via either the `insecure-skip-tls-verify` cluster setting in the kubeconfig file, or via the `--insecure-skip-tls-verify` cli option. This is because the server certificate common name won't match the ngrok domain that the client connects to.

**Comment by jrobsonchase** [comment]
This is soon to get _even easier_ with first-class TLS edge support. Stay tuned!

**Comment by CK-Ward** [comment]
TLS Edge support is complete.
